@startuml
(Керування артефактами) as (КА)
(КА)<..(Зміна артефакту)
(КА)<..(Створення артефакту)
(КА)<..(Видалення артефакту)

(Керування групами артефактів)as (КГА)
(КА) --> (КГА)
(КГА)<..(Видалення групи)
(КГА)<..(Створення нової групи)
(КГА)<..(Зміна групи)
@enduml