@startuml

class Операція{
* Ім'я
}
class Роль{
* Ім'я
}
class Право{
}
class "Тип артефакту"{
* Ім'я
}
class Артефакт{
* Ім'я
* Опис
}
class Призначення{
* Дата
}
class Користувач{
* Email
* Login
}
class Проект{
* Номер
* Іконка
* Назва
}

Операція "1,1" --- "0,*" Право
Право "0..*" -right "1,1" Роль
Право "0..*" --- "1,1" "Тип артефакту"
"Тип артефакту" "1,1" --- "0,*" Артефакт
Роль "1,1" --- "0,*" Призначення
Призначення "0,*" -right "1,1" Користувач
Призначення "1,1" --- "0,*" Проект
@enduml