@startuml
:Зареєстрований користувач: as User
User --> (Вхід у систему)
User --> (Стати учасником \nпроекту)
(Стати учасником \nпроекту) <.. (Прийняти запрошення\n на участь)
(Стати учасником \nпроекту) <.. (Подати заявку \nна участь)
User --> (Перегляд проекту)
User --> (Зміна профілю)
(Зміна профілю) <.. (Зміна інформації профілю)
(Зміна профілю) <.. (Видалення профілю)

@enduml