@startuml
:учасник проекту: as user
user--->(Робота \nнад проектом)
user--->(Оформити \nпідписку)
(Робота \nнад проектом)--->(Управління \nособистими задачами)
(Робота \nнад проектом)--->(Додавання \nкоментарів\nдо задач)
(Управління \nособистими задачами)<...(Зміна \nзадачі)
(Управління \nособистими задачами)<...(Створення задачі)
(Управління \nособистими задачами)<...(Видалення задачі)
(Управління \nособистими задачами)<...(Зміна \nстатусу задачі)
(Оформити \nпідписку)<...(Щорічна \nпідписка)
(Оформити \nпідписку)<...(Щомісячна\nпідписка)
@endum
